<?php

namespace Database\Seeders;

use App\Models\Warehouse\Brand;
use App\Models\Warehouse\Category;
use App\Traits\GetRandomPrice;
use Faker\Factory as Faker;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class ProductsTableSeeder extends Seeder
{

    use GetRandomPrice;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $devices = array(
            "Acer Liquid Z205",
            "Acer Liquid Z205 Dual Sim",
            "ALCATEL 10.13",
            "Alcatel 1035x",
            "ALCATEL 1B",
            "Alcatel 1S 2019",
            "Alcatel 20.04 SENIOR",
            "Alcatel 20.12G",
            "Alcatel 3 5052D",
            "Alcatel 30.26",
            "ALCATEL 3V Dual Sim",
            "Alcatel 5042x",
            "Alcatel 5051X Pop 4",
            "Alcatel Idol 4 6055K",
            "Alcatel One Touch 1013X",
            "Alcatel One Touch 7048X Go Play",
            "Alcatel One Touch Idol 2 Mini S",
            "Alcatel One Touch Pixi 3 4027X",
            "Alcatel OneTouch Idol 6030X",
            "Alcatel OneTouch POP C7",
            "ALCATEL Orange Rise 30",
            "Alcatel Pixi 4  4034D",
            "Alcatel POP C7 DUAL SIM",
            "Alcatel Shine",
            "ALLVIEW L6",
            "ALLVIEW L6 DUAL SIM",
            "Apple iPhone 11",
            "Apple iPhone 11 Pro",
            "Apple iPhone 11 Pro Max",
            "Apple iPhone 12",
            "Apple iPhone 12 Mini",
            "Apple iPhone 12 pro",
            "Apple iPhone 12 Pro Max",
            "APPLE IPHONE 13",
            "Apple iPhone 13 Mini",
            "Apple Iphone 13 pro",
            "Apple iPhone 13 Pro Max",
            "Apple Iphone 14",
            "Apple Iphone 14 Pro",
            "APPLE IPHONE 14 PRO MAX",
            "Apple iPhone 4",
            "Apple iPhone 4S",
            "Apple iPhone 5",
            "Apple iPhone 5C",
            "Apple iPhone 5S",
            "Apple iPhone 6",
            "Apple iPhone 6 Plus",
            "Apple iPhone 6S",
            "Apple iPhone 6S Plus",
            "Apple iPhone 7",
            "Apple iPhone 7 Plus",
            "Apple iPhone 8",
            "Apple iPhone 8 Plus",
            "Apple iPhone SE",
            "Apple iPhone SE 2020",
            "Apple iPhone SE 2022",
            "Apple iPhone X",
            "Apple iPhone XR",
            "Apple iPhone XS",
            "Apple iPhone XS Max",
            "Apple Watch SE 44mm",
            "Archos Core 62s",
            "Archos Neon",
            "Asus Zenfone 2",
            "Asus Zenfone 5",
            "Asus Zenfone 8",
            "ASUS Zenfone Max 3",
            "Asus Zenfone Max Pro M1",
            "Asus Znenfon Go",
            "Asus Znenfon Go 5,5",
            "BlackBerry PASSPORT",
            "BlackBerry 8520",
            "BlackBerry 9300",
            "BlackBerry 9320 Curve",
            "BlackBerry 9360",
            "BlackBerry 9380",
            "BlackBerry 9700",
            "BlackBerry 9720",
            "BlackBerry 9900 Bold",
            "Blackberry CLASSIC",
            "BlackBerry KEYone",
            "BlackBerry Leap",
            "BlackBerry Priv",
            "BlackBerry Q10",
            "BlackBerry Q5",
            "blackberry sth100-2",
            "BlackBerry Z30",
            "Blackview bv6600",
            "Bravis  A501",
            "CAT B15Q",
            "CAT B30",
            "CAT B30 Dual Sim",
            "CAT S60",
            "Dodge x5",
            "Google Pixel 1",
            "Google Pixel 2",
            "Google Pixel 6",
            "Google Pixel 7 pro",
            "Haier W858",
            "MyPhone Hammer Explorer",
            "Honor 10 Lite",
            "Honor 5X",
            "HONOR 6X BLN-L21",
            "Honor 9X",
            "Honor X4",
            "HTC 10",
            "HTC 825",
            "HTC Desire 12 Dual Sim",
            "HTC Desire 12s",
            "HTC Desire 20 Pro",
            "HTC DESIRE 300",
            "Htc Desire 510",
            "HTC Desire 526 Dual Sim",
            "HTC Desire 530",
            "HTC Desire 610",
            "HTC Desire 620",
            "HTC Desire 620 Dual Sim",
            "HTC Desire 620G Dual Sim",
            "HTC Desire 626",
            "HTC Desire 626G DUAL SIM",
            "HTC Desire 650",
            "HTC Desire 820",
            "HTC Desire 825",
            "HTC Desire X",
            "Htc m9 prime camera edition",
            "HTC One A9",
            "HTC ONE A9 2PQ9100",
            "Htc One A9s",
            "Htc One M7",
            "HTC ONE M8",
            "HTC One M8s",
            "HTC ONE M9",
            "HTC One M9 Prime Camera Edition",
            "HTC One Mini 2",
            "HTC Onwe m8S",
            "HTC OPE6400",
            "Htc U Play",
            "HTC U Ultra",
            "HTC U11",
            "HTC U11 LIFE",
            "HTC U12+ Dual Sim",
            "Huawei Ascend Y550",
            "HUAWEI ENJOY 9E",
            "HUAWEI G6 LTE",
            "HUAWEI G620S",
            "Huawei G8",
            "Huawei Honor 10",
            "Huawei Honor 20 lite",
            "Huawei Honor 4x",
            "HUAWEI HONOR 7",
            "Huawei Honor 7 Lite",
            "Huawei Honor 7A AUM-L29",
            "Huawei Honor 7C LND-L29",
            "Huawei Honor 7S Dua-L22",
            "HUAWEI HONOR 7X BND-L21",
            "Huawei Honor 8 FRD-L09 Dual Sim",
            "Huawei Honor 8 LITE 2017 DUAL SIM",
            "Huawei Honor 8X JSN-L21 4/128GB",
            "Huawei Honor 9",
            "Huawei Honor 9 Lite",
            "Huawei Honor Play",
            "Huawei Mate 10 Lite",
            "Huawei Mate 10 Pro",
            "Huawei Mate 20",
            "Huawei Mate 20 Lite",
            "Huawei Mate 20 Pro",
            "Huawei Mate 8",
            "Huawei Mate 9 Pro LON-L29 Dual Sim",
            "Huawei Mate S Premium",
            "Huawei Nexus",
            "Huawei Nova 5T",
            "HUAWEI NOVA CAN-L11",
            "Huawei Nova Plus MLA-L11",
            "Huawei P Smart 2019",
            "Huawei P Smart FIG-LX1 DUAL SIM",
            "Huawei P Smart Mini",
            "Huawei P Smart Plus",
            "Huawei P Smart Pro STK-L21",
            "Huawei P Smart Z STK-LX1",
            "Huawei P10 Lite",
            "Huawei P10 Plus VKY-L09",
            "Huawei P10 VTR-L29",
            "Huawei P20",
            "Huawei P20 Lite",
            "Huawei P20 Pro",
            "Huawei P30",
            "Huawei P30 Lite",
            "Huawei P30 Pro",
            "Huawei P40 Lite",
            "Huawei P40 lite E",
            "Huawei P40 Pro",
            "Huawei P8",
            "Huawei P8 GRA-L09",
            "Huawei P8 Lite",
            "Huawei P8 Lite Dual Sim",
            "Huawei P8 Lite Single Sim",
            "Huawei P8 Lite Smart",
            "Huawei P8 Lite Smart TAG-L01",
            "Huawei P9 Dual Camera",
            "Huawei P9 Dual Sim",
            "Huawei P9 Lite",
            "Huawei P9 Lite 2017",
            "Huawei P9 Lite mini",
            "Huawei P9 Lite mini SLA-L22 DUAL SIM",
            "Huawei P9 PlusVIE-L09",
            "Huawei Shot X",
            "Huawei Y3",
            "Huawei Y3 II",
            "Huawei Y3-2",
            "Huawei Y5 2017",
            "Huawei Y5 2018",
            "Huawei Y5 2018 DRA-L21",
            "Huawei Y5 2019",
            "Huawei Y5 II",
            "Huawei Y5 II Dual sim CUN-L21",
            "Huawei Y5 Y560",
            "Huawei Y530",
            "Huawei Y5p",
            "Huawei Y6 2017",
            "Huawei Y6 2018",
            "Huawei Y6 2019 Dual Sim MDR-LX1",
            "Huawei Y6 II CAM-L21",
            "Huawei Y6 II Compact",
            "Huawei Y6 Pro",
            "Huawei Y6 SCL- L01",
            "Huawei Y600-U20",
            "Huawei Y625",
            "Huawei Y635",
            "Huawei Y6p",
            "Huawei Y6s",
            "Huawei Y7 2019",
            "Huawei Y7 Prime 2018 LDN-L21",
            "Huawei Y7 TRT-LX1",
            "Infinix X676B",
            "Kruger&Matz Live 2 KM0410 Dual Sim",
            "Kruger&Matz Move 5 KM0432 Dual Sim",
            "Lenovo A2010",
            "Lenovo A2010-a",
            "Lenovo A319 RocStar",
            "Lenovo B Dual Sim A2016A40",
            "Lenovo C2 K10a40 Dual Sim",
            "Lenovo K3 Note",
            "Lenovo k5",
            "Lenovo K6 Dual",
            "Lenovo K6 Note Dual Sim",
            "Lenovo Moto G4 PLUS",
            "Lenovo Moto G5",
            "Lenovo Moto G5s",
            "Lenovo P2",
            "Lenovo Vibe Z2 Pro K920",
            "Lg e460",
            "LG F60",
            "LG G Flex",
            "LG G Flex 2",
            "LG G Pro Lite",
            "LG G Pro Lite Dual Sim D686",
            "LG G2 LG-D802",
            "LG G2 Mini D620R",
            "LG G3",
            "LG G3s D722",
            "LG G4",
            "LG G4C H525n",
            "LG G4s",
            "LG G5",
            "LG G5 SE H840",
            "LG G6 LG-H870",
            "LG G7 Fit LM-Q850EMW",
            "LG G8 X Thinq",
            "LG G8S Thinq",
            "LG Joy H220",
            "LG K10 2017 Dual Sim M250E",
            "LG K10 2017 Singel Sim",
            "LG K10 Dual Sim",
            "LG K10 Single Sim",
            "LG K11 Dual Sim",
            "LG K22",
            "LG K3 LTE",
            "LG K30",
            "LG K4 2017 M160 Single Sim",
            "LG K4 2017 M160E Dual Sim",
            "LG K4 Lte",
            "LG K40 Dual Sim",
            "LG K40S LM-X430EMW",
            "LG K41S",
            "LG K5 X220",
            "LG K50",
            "LG K500N X SCREEN",
            "LG K7 X210",
            "LG K8",
            "LG K8 2017 M200E DUAL SIM",
            "LG K8 2017 M200n",
            "LG K8 K350n Dual Sim",
            "LG K8 K350n Single Sim",
            "LG K9 Dual LM-X210EMW",
            "LG K9 Single Sim",
            "LG KC550",
            "LG KP500",
            "LG L Bello",
            "LG L Fino",
            "Lg L3",
            "LG L3 II",
            "LG L65",
            "Lg L7",
            "Lg L70",
            "LG L80",
            "LG L9",
            "LG L9 II",
            "Lg L90",
            "LG Leon LTE H340n",
            "Lg Magna",
            "LG NEXUS 4",
            "LG NEXUS 5",
            "Lg Q6 LG-M700A",
            "LG Q7 FIT",
            "LG Q7 LM-Q10EMW",
            "LG Spirit 4G h440n",
            "LG STYLUS 2 K520",
            "LG SWIFT F5 P875",
            "LG V10",
            "LG V30 LG-H930",
            "LG X Cam K580",
            "LG X Power",
            "LG X Power 2",
            "LG Zero",
            "LG S310",
            "Manta TEL2405 Flip Touch",
            "Maxcom Clasic MM142",
            "Maxcom Classic MK241 4G",
            "MAXCOM Classic MM144",
            "Maxcom Classic MM320",
            "Maxcom Classic MM32D",
            "Maxcom Comfort MM38D",
            "Maxcom Comfort MM426",
            "Maxcom Comfort MM428 BB",
            "Maxcom Comfort MM461",
            "MAXCOM Comfort MM760",
            "Maxcom Comfort MM818",
            "Maxcom MM129",
            "Maxcom MM134BB",
            "Maxcom MM135",
            "Maxcom MM136 Dual Sim",
            "Maxcom MM139",
            "MAXCOM MM141",
            "Maxcom MM142",
            "Maxcom MM235",
            "MAXCOM MM238 3G",
            "Maxcom MM330",
            "Maxcom MM426",
            "MAXCOM MM428",
            "Maxcom MM431BB",
            "Maxcom MM432BB",
            "Maxcom MM461BB",
            "Maxcom MM462BB",
            "Maxcom MM560BB",
            "MaxCom MM720BB",
            "MAXCOM MM730",
            "Maxcom MM816",
            "Maxcom MM817",
            "Maxcom MM818",
            "Maxcom MM819BB",
            "Maxcom MM821BB",
            "Maxcom MM824",
            "Maxcom MM824BB",
            "Maxcom MM910",
            "Maxcom MS453",
            "MAXCOM MS505",
            "Maxcom Smart&Strong MS456",
            "Maxcom Strong MM916 3g",
            "Maxcom Strong MM920",
            "Maxton M-60",
            "Maxton M-60 Dual Sim",
            "Meizu M5 16 GB",
            "Meizu M6s",
            "Meizu M6s Wersja Demonstarcyjna Nie Sprzedawać",
            "Meizu M6T",
            "Meizu M6Tx",
            "Meizu M8",
            "Meizu M8 Wersja Demonstarcyjna Nie Sprzedawać",
            "Meizu MX6 DualSIM",
            "Meizu note 2",
            "Meizu Note 8",
            "Microsoft Lumia 532",
            "Microsoft Lumia 535 DS",
            "Microsoft Lumia 535 Dual Sim",
            "Microsoft Lumia 535 Single Sim",
            "Microsoft Lumia 635",
            "MICROSOFT LUMIA 640",
            "MICROSOFT LUMIA 640 LTE",
            "Microsoft Lumia 650",
            "Microsoft Lumia 650 Dual Sim",
            "Microsoft Lumia 950",
            "Microsoft Lumia 950 XL Dual Sim",
            "MOBIOLA GAIA",
            "MOBIOLA INTI",
            "MOBIOLA MB3000 DUAL SIM",
            "MOBIOLA MB3200 DUAL SIM",
            "MOBIOLA MB3200i DUAL SIM",
            "MOBIOLA MB610 DUAL SIM",
            "MOBIOLA MB700",
            "MOBIOLA MB7000",
            "MOBIOLA MB800 DUAL SIM",
            "MOBIOLA PHANTOM",
            "MOBIOLA Z2",
            "Motorola Nexus 6",
            "Motorola Moto Z PLAY",
            "Motorola Moto G",
            "Motorola E20",
            "Motorola E4 Plus",
            "Motorola e40",
            "Motorola E7 Plus",
            "Motorola Edge",
            "Motorola Edge 30 Fusion",
            "Motorola G6 Plus",
            "Motorola G8 Power",
            "Motorola G9 Power XT2091-3",
            "Motorola Mote E5",
            "Motorola Moto 30 ULTRA",
            "MOTOROLA MOTO C PLUS",
            "Motorola Moto E 2Gen XT1524",
            "Motorola Moto E XT1021",
            "Motorola Moto E5 Play",
            "Motorola Moto E5 Plus",
            "Motorola Moto G 3Gen",
            "Motorola moto G 5G Plus",
            "MOTOROLA MOTO G GEN3 XT1541",
            "Motorola Moto G4 XT1622",
            "Motorola Moto G5S PLUS",
            "MOTOROLA MOTO G6",
            "Motorola Moto G6 DualSIM",
            "Motorola Moto G6 Play",
            "Motorola Moto G7",
            "Motorola Moto G7 Play",
            "Motorola Moto G7 Plus",
            "Motorola Moto G7 Power DualSIM",
            "Motorola Moto G8",
            "Motorola Moto G8 Power",
            "Motorola Moto G9",
            "Motorola Moto G9 Play",
            "Motorola Moto G9 PLUS",
            "Motorola Moto X Play XT1562",
            "Motorola Moto X STYLE XT1572",
            "Motorola Moto X XT1092",
            "Motorola Moto X4",
            "motorola moto z",
            "Motorola Moto Z3 Play",
            "Motorola One Action",
            "Motorola One Fusion",
            "Motorola One Macro",
            "Motorola One Vision",
            "motorola one xt1941",
            "Motorola X Force",
            "Motorola X Style",
            "Motorola XT910",
            "Motorola Z2 play",
            "MyPhone Maestro",
            "Myphone 1045 SIMPLY",
            "myphone 1055",
            "Myphone 1062 TALK+",
            "myphone 1065 spectrum",
            "MyPhone 1082 ELEGANT+",
            "MyPhone Artis",
            "MYPHONE C1",
            "MyPhone City XL",
            "MyPhone COMPACT DUAL SIM",
            "MyPhone Cube LTE",
            "Myphone Fun 4",
            "Myphone HALO 2",
            "Myphone HALO 3",
            "Myphone HALO 3 LTE",
            "MYPHONE HALO A+",
            "MYPHONE HALO C",
            "MYPHONE HALO EASY",
            "MYPHONE HALO MINI",
            "MYPHONE HALO mini 2",
            "MYPHONE HALO S",
            "MyPhone Halo X",
            "MyPhone HAMMER",
            "MYPHONE Hammer 2",
            "MyPhone HAMMER 2+ (3G)",
            "MyPhone Hammer 3",
            "MyPhone Hammer 3 Plus",
            "MyPhone HAMMER Active",
            "MyPhone Hammer AXE LTE",
            "MYPHONE HAMMER AXE M LTE",
            "MYPHONE HAMMER AXE PRO",
            "MYPHONE Hammer Bow +",
            "Myphone Hammer Energy",
            "Myphone Hammer Energy 18x9",
            "MyPhone HAMMER Force",
            "MyPhone HAMMER IRON",
            "MyPhone HAMMER IRON 2",
            "MyPhone Hammer Iron 3 LTE",
            "MYPHONE INFINITY G3",
            "MYPHONE IRON II",
            "MyPhone L-Line",
            "MyPhone LUNA",
            "MyPhone Luna II",
            "MYPHONE Maestro",
            "MyPhone Metro",
            "MyPhone MINI DUAL SIM",
            "MyPhone Prime",
            "MyPhone Prime 2",
            "MYPHONE PRIME PLUS",
            "Myphone RUMBA",
            "Myphone Tango",
            "Myphone Tango LTE",
            "Myphone Twist",
            "MyPhone Up",
            "MyPhone Waltz",
            "MyPhone X Pro",
            "NOKIA 1,3",
            "Nokia 100",
            "Nokia 105",
            "Nokia 105 Dual Sim",
            "Nokia 106.1",
            "Nokia 107 Dual Sim",
            "Nokia 108 Dual Sim",
            "Nokia 110",
            "Nokia 110 4G",
            "Nokia 1112",
            "Nokia 130  2017 DUAL SIM",
            "Nokia 130 DUAL SIM",
            "Nokia 150 Dual Sim",
            "Nokia 1600",
            "Nokia 1800",
            "Nokia 2.1 TA-1080",
            "Nokia 210",
            "Nokia 215",
            "Nokia 215 Dual Sim",
            "Nokia 216 DUAL SIM",
            "Nokia 220 DUAL SIM",
            "Nokia 222 Dual Sim",
            "Nokia 225 Dual Sim",
            "Nokia 230 DS",
            "Nokia 2330c",
            "Nokia 2610",
            "Nokia 2700c",
            "Nokia 2720 Flip",
            "Nokia 3 TA-1020",
            "Nokia 3 TA-1032 Dual Sim",
            "Nokia 3.1 DS",
            "Nokia 3.4",
            "Nokia 301",
            "Nokia 302",
            "Nokia 3310",
            "Nokia 3310 2017 DUAL-SIM",
            "Nokia 3410",
            "Nokia 5 TA-1024 SS",
            "Nokia 5 TA-1053 Dual Sim",
            "Nokia 5.1 Plus TA-1105 DS",
            "Nokia 5.1 TA-1075 Dual Sim 2GB 16GB ROM",
            "Nokia 5.1 TA-1075 Dual Sim 3GB 32GB",
            "NOKIA 500",
            "Nokia 515",
            "nokia 535",
            "Nokia 5630 Xpress Music",
            "NOKIA 5800",
            "Nokia 6",
            "Nokia 6.1",
            "Nokia 6021",
            "NOKIA 6210 NAVIGATOR",
            "Nokia 6230i",
            "nokia 625",
            "Nokia 6300",
            "NOKIA 6303",
            "NOKIA 6303i Classic",
            "nokia 6310i",
            "Nokia 7.1",
            "Nokia 7.2 TA-1196 Dual Sim",
            "Nokia 7230",
            "Nokia 8 Dual Sim",
            "Nokia 800 Tough",
            "NOKIA 8110 4G TA-1048",
            "Nokia Asha 210",
            "Nokia Asha 300",
            "Nokia C2-01",
            "Nokia C2-02",
            "Nokia C3",
            "Nokia C5",
            "NOKIA C6-01",
            "NOKIA E52",
            "NOKIA e65",
            "Nokia E66",
            "Nokia E72",
            "NOKIA LUMIA 1020",
            "Nokia Lumia 1320",
            "Nokia Lumia 510",
            "Nokia Lumia 520",
            "Nokia Lumia 530",
            "Nokia Lumia 550",
            "Nokia Lumia 620",
            "Nokia Lumia 625",
            "Nokia Lumia 630",
            "Nokia Lumia 635 RM-974",
            "Nokia Lumia 735",
            "nokia lumia 820",
            "Nokia Lumia 830",
            "Nokia Lumia 925",
            "Nokia Lumia 930",
            "Nokia Microsoft Lumia RM-1090",
            "Nokia N9",
            "Nokia x6",
            "OnePlus 7T",
            "ONEPLUS 3T",
            "OnePlus 5",
            "OnePlus 5T",
            "OnePlus 6T",
            "oppo a12",
            "Oppo A15S",
            "Oppo A31",
            "oppo a32",
            "Oppo A5 2020",
            "Oppo a54S",
            "Oppo A72",
            "oppo a9",
            "Oppo Reno 3 PRO",
            "Oppo Reno 4 Lite",
            "Oppo Reno 4 Z 5G",
            "Oppo Reno 5 Lite",
            "Oppo Reno 5Z",
            "Oppo Reno 6 5G",
            "ORANGE REYO",
            "Oukitel WP17",
            "Overmax Vertis 1810 Kern",
            "Overmax Vertis 1820 Easy",
            "Overmax Vertis 2210 Easy",
            "Overmax Vertis 3511 You",
            "Overmax Vertis 4011 You Case",
            "Overmax Vertis 4011 You Music",
            "Overmax Vertis 4510 EXPI",
            "Overmax Vertis 4520 aim",
            "Overmax Vertis 5010 Expi",
            "Overmax Vertis 5011 Expi",
            "Overmax Vertis 5021 AIM",
            "Overmax Vertis 5025 Expi",
            "Overmax Vertis Braver",
            "Panasonic KX-TU 150EXB",
            "Panasonic KX-TU 150EXC",
            "Panasonic KX-TU 150EXR",
            "Panasonic KX-TU 446EXR",
            "Philips Xenium v377",
            "Prestigio psp3452",
            "QSMART model MB5050",
            "Realme 6",
            "Realme 7i",
            "Realme 8",
            "REALME 9 5G",
            "realme cy25",
            "Realme GT Master Edition",
            "Realme GT Neo 3T",
            "Realme Narzo 50i Prime",
            "Xiaomi Redmi a1",
            "Sagem MyX-1twin",
            "samsung a3 A300FU",
            "Samsung Avila S5230",
            "Samsung B2100 Solid",
            "Samsung C3050",
            "Samsung c3350 Solid",
            "Samsung C3520",
            "Samsung C3530",
            "Samsung C3780",
            "Samsung e1200",
            "Samsung E1200M",
            "Samsung E2210B",
            "Samsung Galaxy a02s",
            "Samsung Galaxy A03S",
            "Samsung Galaxy A04S",
            "Samsung Galaxy A10",
            "Samsung Galaxy A11",
            "Samsung Galaxy A12",
            "Samsung Galaxy A13",
            "Samsung Galaxy A14",
            "Samsung Galaxy A20e",
            "Samsung Galaxy A20s",
            "Samsung Galaxy A21s",
            "Samsung Galaxy A22",
            "Samsung Galaxy A22 5G",
            "Samsung Galaxy A3",
            "Samsung Galaxy A3 2016",
            "Samsung Galaxy A3 2017",
            "Samsung Galaxy A30",
            "Samsung Galaxy A30s",
            "Samsung Galaxy A32",
            "Samsung Galaxy A32 5G",
            "Samsung Galaxy A33 5G",
            "Samsung Galaxy A34 5G",
            "Samsung Galaxy A40",
            "Samsung Galaxy A41",
            "Samsung Galaxy A42 5G",
            "Samsung Galaxy A5",
            "Samsung Galaxy A5 2016",
            "Samsung Galaxy A5 2017",
            "Samsung Galaxy A50",
            "Samsung Galaxy A51",
            "Samsung Galaxy A52",
            "Samsung Galaxy A52s",
            "Samsung Galaxy A53 5G",
            "Samsung Galaxy A54",
            "Samsung Galaxy A6 A600FN/DS",
            "Samsung Galaxy A6+ 2018",
            "Samsung Galaxy A7",
            "Samsung Galaxy A7 2018",
            "Samsung Galaxy A70",
            "Samsung Galaxy A71 (SM-A715F/DS)",
            "Samsung Galaxy a72",
            "Samsung Galaxy A8 2018",
            "Samsung Galaxy A8 Plus",
            "Samsung Galaxy A80",
            "Samsung Galaxy A9 2018",
            "Samsung Galaxy Ace 2 i8160",
            "Samsung Galaxy Ace 4",
            "Samsung Galaxy Ace S5830",
            "Samsung Galaxy Alpha",
            "Samsung Galaxy Apollo i5800",
            "Samsung Galaxy Corby B5310",
            "SAMSUNG GALAXY CORE",
            "Samsung Galaxy Core 2",
            "Samsung Galaxy Core Plus",
            "Samsung Galaxy Core Prime SM-G360F",
            "Samsung Galaxy Fame",
            "samsung galaxy grand 2 sm-g7105",
            "Samsung Galaxy Grand Neo",
            "Samsung Galaxy Grand Prime",
            "Samsung Galaxy J1",
            "Samsung Galaxy J1 2016 J120FN",
            "Samsung Galaxy J1 Mini SM-J105h/ Dual Sim",
            "Samsung Galaxy J2 Prime",
            "Samsung galaxy J3",
            "Samsung Galaxy J3 2016",
            "Samsung Galaxy J3 2017",
            "Samsung Galaxy J4+",
            "Samsung Galaxy J5",
            "Samsung Galaxy J5 2016",
            "Samsung Galaxy J5 2017 J530 Dual Sim",
            "Samsung Galaxy J5 SM-J500FN",
            "Samsung Galaxy J6",
            "Samsung Galaxy J6+ SM-J610/DS",
            "Samsung Galaxy J7 2016",
            "SAMSUNG GALAXY J7 2017 DUAL SIM",
            "Samsung Galaxy M11",
            "Samsung Galaxy M12",
            "Samsung galaxy M13",
            "Samsung Galaxy M21",
            "Samsung Galaxy M23 5g",
            "Samsung Galaxy M31s",
            "Samsung Galaxy M51",
            "Samsung Galaxy M52 5G",
            "SAMSUNG GALAXY MEGA I9205",
            "SAMSUNG GALAXY MINI",
            "Samsung Galaxy Note",
            "Samsung Galaxy Note 10",
            "Samsung Galaxy Note 10 lite",
            "Samsung Galaxy Note 10 Plus",
            "Samsung Galaxy Note 2",
            "Samsung Galaxy Note 20 Ultra",
            "Samsung Galaxy Note 3",
            "Samsung Galaxy Note 4 N910C",
            "Samsung Galaxy Note 4 n910f",
            "SAMSUNG GALAXY NOTE 4 SM-N9100 DUAL SIM",
            "Samsung Galaxy note 5",
            "Samsung Galaxy Note 8 SM-N950F/DS",
            "Samsung Galaxy Note 9",
            "SAMSUNG GALAXY NOTE EDGE",
            "Samsung Galaxy Note II LTE",
            "Samsung Galaxy S i9001",
            "Samsung Galaxy S10",
            "Samsung Galaxy S10 lite",
            "Samsung Galaxy S10 Plus",
            "Samsung Galaxy S10e",
            "Samsung galaxy S2",
            "Samsung Galaxy S2 PLUS",
            "Samsung Galaxy S20 Fe",
            "Samsung Galaxy S20 FE G780F/DS",
            "Samsung Galaxy S20 Plus",
            "Samsung Galaxy S20 Plus 5G",
            "Samsung Galaxy S20 SM-G980F/DS",
            "Samsung Galaxy S20 SM-G981 5G",
            "Samsung Galaxy S20 Ultra",
            "Samsung Galaxy S21 5G",
            "Samsung Galaxy S21 FE",
            "Samsung Galaxy S21 Plus",
            "Samsung Galaxy S21 Ultra 128gb",
            "Samsung Galaxy S22",
            "Samsung Galaxy S22 Plus",
            "Samsung Galaxy S22 Ultra",
            "Samsung Galaxy S23 Ultra",
            "Samsung Galaxy S3 i9300",
            "Samsung Galaxy S3 Mini",
            "Samsung Galaxy S3 Neo",
            "Samsung Galaxy S4",
            "Samsung Galaxy S4 Active",
            "Samsung Galaxy S4 Mini",
            "Samsung Galaxy S5",
            "Samsung Galaxy S5 Active",
            "Samsung Galaxy S5 Mini SM-G800F",
            "Samsung Galaxy S5 Neo G903F",
            "Samsung Galaxy S6",
            "Samsung Galaxy S6 Edge",
            "Samsung Galaxy S6 Edge Plus",
            "Samsung Galaxy S7 Edge",
            "Samsung Galaxy S7 G930F",
            "Samsung Galaxy S8",
            "Samsung Galaxy S8 Plus SM-G955F",
            "Samsung Galaxy S9",
            "Samsung Galaxy S9 Plus",
            "Samsung Galaxy Trend 2 Lite",
            "Samsung Galaxy Trend Plus",
            "Samsung galaxy xcover 2",
            "Samsung Galaxy Xcover 3",
            "Samsung Galaxy Xcover 4 SM-G390F",
            "Samsung Galaxy Xcover 4s SM-G398FN/DS",
            "Samsung Galaxy Xcover 550 B550H",
            "Samsung Galaxy Xcover S5690",
            "Samsung Galaxy Young S6310",
            "Samsung Galaxy Z Fold3 5G SM-F926",
            "Samsung Galaxy Z-Flip 4 5G",
            "Samsung Galaxy ZFlip 3 5G",
            "Samsung Gear VR",
            "Samsung GT-E1150",
            "Samsung gt-e2330b",
            "Samsung GT-S561",
            "Samsung GT-S6310N",
            "Samsung J5",
            "Samsung J5 2017 J550F/DS",
            "Samsung J5 2017 J553F/DS",
            "SAMSUNG MONTE",
            "Samsung S Advance i9070",
            "Samsung S3570",
            "Samsung S5610",
            "Samsung S5611",
            "Samsung S6 Edge",
            "Samsung S611",
            "SAMSUNG SGH D 600E",
            "Samsung Solid B2700",
            "Samsung Solid B2710",
            "Samsung Solid E2370",
            "Samsung X510",
            "Samsung X520",
            "Samsung Xcover  C3350",
            "Samsung Xcover 2 S7710",
            "Samsung Xcover 5",
            "Samsung B5310 Corby PRO",
            "Samsung SGH-J700",
            "SonyEricsson J20 Hazel",
            "SonyEricsson K300i",
            "SonyEricsson W880i",
            "SonyEricsson Xperia Arc S",
            "Sony M4 Aqua E2303",
            "Sony Xperia 1",
            "SONY XPERIA 10",
            "Sony Xperia 10 II",
            "Sony Xperia 10 III",
            "Sony Xperia 10 Plus",
            "Sony Xperia C4 E5303",
            "Sony Xperia E1",
            "Sony Xperia E3 D2203",
            "Sony Xperia E4 E2105 Single Sim",
            "Sony Xperia E4 E2115 Dual Sim",
            "Sony Xperia E5 F3311",
            "Sony Xperia J",
            "SONY XPERIA L C2105",
            "Sony Xperia L1",
            "Sony Xperia L4",
            "Sony Xperia M",
            "Sony Xperia M2",
            "Sony Xperia M2 Aqua",
            "Sony Xperia M2 LTE D2303",
            "SONY XPERIA M4 AQUA",
            "Sony Xperia M4 Aqua E2303",
            "Sony Xperia M5",
            "Sony Xperia P LT22i",
            "Sony Xperia SP",
            "Sony Xperia T",
            "sony xperia t2",
            "Sony Xperia T3",
            "Sony Xperia Tipo",
            "Sony Xperia U",
            "Sony Xperia X",
            "Sony Xperia X Compact",
            "Sony Xperia X F5121",
            "Sony Xperia X Performance",
            "Sony Xperia XA F3111",
            "Sony Xperia XA Ultra  F3211",
            "sony xperia xa1",
            "Sony Xperia XA1 Plus G3421",
            "Sony Xperia XA1 Ultra  G3212",
            "Sony Xperia XA2 H3113",
            "Sony Xperia XZ F8331",
            "Sony Xperia XZ Premium (G8141)",
            "Sony Xperia XZ1 Compact",
            "Sony Xperia XZ1 G8342",
            "Sony Xperia XZ2 (H8216)",
            "Sony Xperia Z",
            "SONY XPERIA Z C6603",
            "Sony Xperia Z Ultra",
            "Sony Xperia Z1",
            "Sony Xperia Z1 C6903",
            "SONY XPERIA Z1 COMPACT",
            "Sony XPERIA Z2",
            "Sony Xperia Z3 compact D5803",
            "Sony Xperia Z3 D6603",
            "Sony Xperia Z3 D6633",
            "Sony Xperia Z3 Plus E6553",
            "Sony Xperia Z3+ E6553",
            "Sony Xperia Z4",
            "Sony Xperia Z5 Compact E5823",
            "Sony Xperia Z5 Dual Sim E6633",
            "Sony Xperia Z5 E6653",
            "Sony Xperia Z5 Premium",
            "TELEFUNKEN LTE LIMA",
            "Telefunken Outdoor LTE",
            "Timmy M20",
            "Toshiba tg01",
            "TP-LINK NEFFOS C5",
            "TP-LINK NEFFOS C5 Max",
            "TP-LINK NEFFOS C5A",
            "TP-LINK NEFFOS C7",
            "TP-LINK NEFFOS C9A Dual Sim",
            "TP-LINK NEFFOS X1 Dual Sim",
            "TP-LINK NEFFOS X1 Lite Dual Sim",
            "TP-LINK NEFFOS X1 MAX Dual Sim",
            "TP-LINK NEFFOS X9 Dual Sim",
            "TP-LINK NEFFOS Y50 LTE DUAL SIM",
            "TP-LINK NEFFOS Y5L",
            "TP-LINK NEFFOS Y5L Sunny Yellow",
            "TP-LINK NEFFOS Y5S",
            "Vivo Y11s V2028",
            "VIVO Y33S",
            "WIKO Jerry 5 Dual Sim",
            "WIKO Lenny 2 Dual Sim",
            "WIKO Lenny 3 Dual Sim",
            "Xiaomi 11T Pro",
            "Xiaomi 12 5G",
            "Xiaomi 13 5G",
            "Xiaomi Mi 10 5G",
            "Xiaomi Mi 10 Lite 5G",
            "Xiaomi MI 10T 5G",
            "XIAOMI MI 10T Pro 5G",
            "Xiaomi Mi 11",
            "Xiaomi Mi 11 Lite",
            "Xiaomi Mi 11T Pro",
            "Xiaomi Mi 4C",
            "Xiaomi Mi 5s Plus",
            "Xiaomi Mi 6",
            "Xiaomi Mi 8",
            "Xiaomi Mi 8 Lite",
            "Xiaomi Mi 9",
            "Xiaomi Mi 9 Lite",
            "Xiaomi Mi 9 se",
            "Xiaomi Mi 9T",
            "Xiaomi Mi 9T Pro",
            "Xiaomi Mi A1",
            "Xiaomi Mi A2",
            "Xiaomi Mi A2 Lite",
            "Xiaomi Mi Max",
            "Xiaomi Mi Max 3",
            "Xiaomi Mi Mix 2S",
            "Xiaomi Mi Mix 3",
            "Xiaomi Mi Note 10",
            "Xiaomi Mi Note 10 Lite",
            "Xiaomi Mi Play",
            "Xiaomi Note 11",
            "Xiaomi Note 11 Pro",
            "Xiaomi Poco F2 PRO",
            "Xiaomi Poco M3",
            "Xiaomi Pocophone",
            "Xiaomi Pocophone POCO X3 NFC",
            "Xiaomi Pocophone POCO X3 Pro",
            "Xiaomi Redmi 10C",
            "Xiaomi Redmi 2",
            "Xiaomi Redmi 3S",
            "Xiaomi Redmi 4A",
            "Xiaomi Redmi 4X",
            "Xiaomi Redmi 5",
            "Xiaomi Redmi 5 Plus",
            "Xiaomi Redmi 5A",
            "Xiaomi Redmi 6",
            "Xiaomi Redmi 6A",
            "Xiaomi Redmi 7",
            "Xiaomi Redmi 7a",
            "Xiaomi Redmi 8",
            "Xiaomi Redmi 8a",
            "Xiaomi Redmi 9",
            "Xiaomi Redmi 9A",
            "Xiaomi Redmi 9C",
            "Xiaomi Redmi 9T",
            "Xiaomi Redmi Mi 4",
            "Xiaomi Redmi Note 10",
            "Xiaomi Redmi Note 10 5G",
            "Xiaomi Redmi Note 10 Pro",
            "Xiaomi Redmi Note 10s",
            "Xiaomi Redmi note 11",
            "Xiaomi Redmi Note 12",
            "Xiaomi Redmi Note 3",
            "Xiaomi Redmi Note 3 Pro",
            "Xiaomi Redmi Note 4",
            "Xiaomi Redmi Note 5",
            "Xiaomi Redmi Note 5A",
            "Xiaomi Redmi Note 6 Pro",
            "Xiaomi Redmi Note 7",
            "Xiaomi redmi note 7 pro",
            "Xiaomi Redmi Note 8 Pro",
            "Xiaomi Redmi Note 8T",
            "Xiaomi Redmi Note 9",
            "Xiaomi Redmi Note 9 Pro",
            "Xiaomi Redmi Note 9S",
            "Xiaomi Redmi Pro",
            "Xiaomi Redmi S2",
            "Xiaomi Mi 5",
            "xiaomi redmi 4s",
            "Sony xperia go",
            "Sony Xperia XA F3111",
            "Asus Zenfone Max Pro M1",
            "ZTE Blade A310",
            "ZTE Blade A452",
            "ZTE Blade L5",
            "ZTE Blade V7 Lite",
            "ZTE R528",
            "ZTE R528 DUAL SIM",
        );

        // $updatedDevices = array_map(function ($item) {
        //     return Str::after($item, ' ');
        // }, $devices);

        $updatedDevices = array_reduce($devices, function ($carry, $item) {
            $key = Str::before($item, ' ');
            $value = Str::after($item, ' ');
            $carry[$key] = $value;
            return $carry;
        }, []);

        // $others = [
        //     "TELEFON KOMÓRKOWY",
        //     "Telefon Komórkowy Samsung",
        // ];

        $words = [
            'Alpha', 'Beta', 'Gamma', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 'India', 'Juliet',
            'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa', 'Quebec', 'Romeo', 'Sierra', 'Tango',
            'Uniform', 'Victor', 'Whiskey', 'X-ray', 'Yankee', 'Zulu', 'Red', 'Blue', 'Green', 'Yellow',
            'Purple', 'Black', 'White', 'Silver', 'Golden', 'Smart', 'Pro', 'Max', 'Ultra', 'Mini',
            'Copper', 'Bronze', 'Platinum', 'Ruby', 'Emerald', 'Sapphire', 'Opal', 'Jade', 'Topaz', 'Onyx',
            'Ivory', 'Coral', 'Turquoise', 'Amber', 'Pearl', 'Quartz', 'Garnet', 'Amethyst', 'Diamond', 'Tanzanite',
            'Cobalt', 'Magenta', 'Teal', 'Indigo', 'Maroon', 'Charcoal', 'Crimson', 'Beige', 'Cyan', 'Olive',
            'Mauve', 'Fuchsia', 'Cerulean', 'Lavender', 'Salmon', 'Slate', 'Periwinkle', 'Ochre', 'Plum', 'Burgundy',
            'Sunset', 'Dawn', 'Twilight', 'Noon', 'Dusk', 'Midnight', 'Storm', 'Breeze', 'Fog', 'Rain',
            'Snow', 'Hail', 'Thunder', 'Lightning', 'Gale', 'Zephyr', 'Gust', 'Mist', 'Drizzle', 'Tempest',
            'Aurora', 'Blaze', 'Cloud', 'Dew', 'Echo', 'Frost', 'Glimmer', 'Halo', 'Ice', 'Jewel',
            'Karma', 'Lush', 'Moon', 'Nebula', 'Orbit', 'Prism', 'Quasar', 'Radiance', 'Shimmer', 'Tide',
            'Utopia', 'Vortex', 'Wisp', 'Xenon', 'Yacht', 'Zenith', 'Abyss', 'Bolt', 'Cascade', 'Dawn',
            'Eclipse', 'Flash', 'Gleam', 'Horizon', 'Ink', 'Jade', 'Krypton', 'Lava', 'Mystic', 'Nova'
        ];

        $gsmProducts = [
            "Jelly Case", "Silicone Case", "Ładowarka samochodowa", "Ładowarka indukcyjna",
            "Etui pancerne", "Powerbank", "Szkło hartowane", "Folia ochronna", "Kabel USB-C",
            "Kabel Lightning", "Uchwyt samochodowy", "Etui na pas", "Słuchawki Bluetooth",
            "Adapter USB-C na Jack 3,5mm", "Smartwatch", "Stacja dokująca", "Selfie stick",
            "Uchwyt rowerowy", "Etui portfelowe", "PopSocket", "Głośnik Bluetooth", "Etui wodoodporne",
            "Karta pamięci MicroSD", "Powerbank solarny", "Zestaw głośnomówiący", "Obiektyw do telefonu",
            "Hub USB", "Klawiatura Bluetooth", "Rysik do smartfona", "Etui z funkcją stand",
            "Rękawiczki dotykowe", "Bumper", "Etui magnetyczne", "Ładowarka sieciowa", "Kamera do smartfona",
            "Zewnętrzna antena GSM", "Odbiornik TV do telefonu", "Etui z nadrukiem", "Osłona na aparat",
            "Uchwyt na palec", "Etui skórzane", "Etui z baterią", "Organizer na kable", "Ekran prywatności",
            "Etui z klapką", "Zestaw ładowania bezprzewodowego", "Lokalizator Bluetooth", "Słuchawki przewodowe",
            "Smartband", "Etui przeciwpyłowe",
            "Ochronne etui na słuchawki", "Adapter SIM", "Lupa do telefonu", "Kabel HDMI", "Głośnik przenośny",
            "Podstawka chłodząca", "Głośnik bezprzewodowy", "Etui ochronne na aparat", "Zestaw narzędzi do naprawy",
            "Ładowarka zewnętrzna", "Kabel audio", "Słuchawki gamingowe", "Ochraniacz ekranu", "Torba na sprzęt",
            "Podstawka do ładowania", "Rysik z funkcją pióra", "Mikrofon do telefonu", "Etui sportowe", "Kabel magnetyczny",
            "Etui na dokumenty", "Kamera akcji", "Powerbank z lampką", "Ładowarka bezprzewodowa do zegarka", "Kieszonkowy projektor",
            "Pokrowiec na smartfona", "Ładowarka podróżna", "Podstawka do telefonu", "Zestaw do czyszczenia ekranu"
        ];

        $categoryIds = DB::table('categories')->pluck('id')->toArray();
        $brands = Brand::select(['id', 'name'])->get();

        $numberOfProducts = 1000;

        $data = [];

        for ($i = 0; $i < $numberOfProducts; $i++) {

            $categoryId = $categoryIds[array_rand($categoryIds)];

            $brand = $brands->random();
            $brandId = $brand->id;

            $productName = $gsmProducts[rand(0, count($gsmProducts) - 1)] . ' ' . $words[rand(0, count($words) - 1)] . ' ' . $words[rand(0, count($words) - 1)];
            $price = rand(1,3) === 3 ? $this->getRandomPrice() : 0;
            $data[] = [
                'category_id' => $categoryId,
                'brand_id' => $brandId,
                'suggested_retail_price' => $price,
                'name' => $productName,
                'slug' => Str::slug($productName),
                'is_device' => false,
                'created_at' => now(),
                'updated_at' => now()
            ];
        }

        $phones_category_id = Category::where('plural_name', 'Telefony')->first()->id;

        foreach($updatedDevices as $brandName => $modelName)
        {


            $slug = Str::slug($modelName);
            $brand = Brand::where('slug', Str::slug($brandName))->first();

            if(!$brand) {
                abort(403, 'Error, brand slug dont exists');
                // dd($brandName);
            }

            $data[] = [
                'category_id' => $phones_category_id,
                'brand_id' => $brand->id,
                'suggested_retail_price' => 0,
                'name' => $modelName,
                'slug' => $slug,
                'is_device' => true,
                'created_at' => now(),
                'updated_at' => now()
            ];
        }

        DB::table('products')->insert($data);
    }
}
